### PR TITLE
Error types

### PR DESCRIPTION
**Pull request by Lumyo**

### CODE REVIEW

**Comment by Lumyo** [comment]
<details>
<summary>Contract size changes</summary>

```
 ·--------------------------------|-------------|---------------·
 |  Contract Name                 ·  Size (KB)  ·  Change (KB)  │
 ·································|·············|················
 |  MerkleProof                   ·      0.086  ·               │
 ·································|·············|················
 |  ECDSA                         ·      0.086  ·               │
 ·································|·············|················
 |  MetamorphicFactoryStorage     ·      0.086  ·               │
 ·································|·············|················
 |  ERC165Storage                 ·      0.086  ·               │
 ·································|·············|················
 |  ECDSAMultisigWalletStorage    ·      0.086  ·               │
 ·································|·············|················
 |  PausableStorage               ·      0.086  ·               │
 ·································|·············|················
 |  AddressUtils                  ·      0.086  ·               │
 ·································|·············|················
 |  ArrayUtils                    ·      0.086  ·               │
 ·································|·············|················
 |  EnumerableMap                 ·      0.086  ·               │
 ·································|·············|················
 |  Math                          ·      0.086  ·               │
 ·································|·············|················
 |  EnumerableSet                 ·      0.086  ·               │
 ·································|·············|················
 |  UintUtils                     ·      0.086  ·               │
 ·································|·············|················
 |  SafeCast                      ·      0.086  ·               │
 ·································|·············|················
 |  ReentrancyGuardStorage        ·      0.086  ·               │
 ·································|·············|················
 |  SafeERC20                     ·      0.086  ·               │
 ·································|·············|················
 |  AccessControlStorage          ·      0.086  ·               │
 ·································|·············|················
 |  OwnableStorage                ·      0.086  ·               │
 ·································|·············|················
 |  SafeOwnableStorage            ·      0.086  ·               │
 ·································|·············|················
 |  UpgradeableProxyStorage       ·      0.086  ·               │
 ·································|·············|················
 |  ERC1271StoredStorage          ·      0.086  ·               │
 ·································|·············|················
 |  DiamondBaseStorage            ·      0.086  ·               │
 ·································|·············|················
 |  ERC1155BaseStorage            ·      0.086  ·               │
 ·································|·············|················
 |  ERC1155EnumerableStorage      ·      0.086  ·               │
 ·································|·············|················
 |  ERC1155MetadataStorage        ·      0.086  ·               │
 ·································|·············|················
 |  ERC1404BaseStorage            ·      0.086  ·               │
 ·································|·············|················
 |  ERC20BaseStorage              ·      0.086  ·               │
 ·································|·············|················
 |  ERC20ImplicitApprovalStorage  ·      0.086  ·               │
 ·································|·············|················
 |  ERC20MetadataStorage          ·      0.086  ·               │
 ·································|·············|················
 |  ERC20PermitStorage            ·      0.086  ·               │
 ·································|·············|················
 |  ERC4626BaseStorage            ·      0.086  ·               │
 ·································|·············|················
 |  ERC20SnapshotStorage          ·      0.086  ·               │
 ·································|·············|················
 |  ERC721BaseStorage             ·      0.086  ·               │
 ·································|·············|················
 |  ERC721MetadataStorage         ·      0.086  ·               │
 ·································|·············|················
 |  ProxyMock                     ·      0.135  ·       -0.066  │
 ·································|·············|················
 |  ERC165Mock                    ·      0.368  ·       -0.051  │
 ·································|·············|················
 |  ReentrancyGuardMock           ·      0.373  ·       -0.099  │
 ·································|·············|················
 |  MathMock                      ·      0.446  ·               │
 ·································|·············|················
 |  PausableMock                  ·      0.500  ·       -0.077  │
 ·································|·············|················
 |  UpgradeableProxyOwnableMock   ·      0.514  ·       -0.114  │
 ·································|·············|················
 |  UpgradeableProxyMock          ·      0.517  ·       -0.066  │
 ·································|·············|················
 |  MerkleProofMock               ·      0.577  ·               │
 ·································|·············|················
 |  ERC1271StoredMock             ·      0.620  ·               │
 ·································|·············|················
 |  CloneFactoryMock              ·      0.629  ·       -0.099  │
 ·································|·············|················
 |  ManagedProxyMock              ·      0.699  ·       -0.135  │
 ·································|·············|················
 |  SafeOwnableMock               ·      0.714  ·       -0.117  │
 ·································|·············|················
 |  OwnableMock                   ·      0.717  ·       -0.051  │
 ·································|·············|················
 |  MetamorphicFactoryMock        ·      0.726  ·       -0.051  │
 ·································|·············|················
 |  FactoryMock                   ·      0.776  ·       -0.099  │
 ·································|·············|················
 |  ManagedProxyOwnableMock       ·      0.852  ·       -0.135  │
 ·································|·············|················
 |  ERC1271OwnableMock            ·      0.920  ·       -0.211  │
 ·································|·············|················
 |  MulticallMock                 ·      0.923  ·               │
 ·································|·············|················
 |  ERC20MetadataMock             ·      0.940  ·               │
 ·································|·············|················
 |  MinimalProxyFactoryMock       ·      0.952  ·       -0.099  │
 ·································|·············|················
 |  ECDSAMock                     ·      0.995  ·       -0.211  │
 ·································|·············|················
 |  UintUtilsMock                 ·      1.285  ·       -0.062  │
 ·································|·············|················
 |  ArrayUtilsMock                ·      1.379  ·               │
 ·································|·············|················
 |  ERC1155MetadataMock           ·      1.422  ·               │
 ·································|·············|················
 |  ERC721MetadataMock            ·      1.733  ·       -0.076  │
 ·································|·············|················
 |  ERC20BaseMock                 ·      2.085  ·       -0.530  │
 ·································|·············|················
 |  AccessControlMock             ·      2.200  ·       -0.058  │
 ·································|·············|················
 |  ERC20ImplicitApprovalMock     ·      2.226  ·       -0.530  │
 ·································|·············|················
 |  AddressUtilsMock              ·      2.312  ·       -0.246  │
 ·································|·············|················
 |  ERC20ExtendedMock             ·      2.349  ·       -0.649  │
 ·································|·············|················
 |  DiamondBaseMock               ·      2.556  ·       -0.815  │
 ·································|·············|················
 |  ECDSAMultisigWalletMock       ·      2.629  ·       -0.783  │
 ·································|·············|················
 |  ERC1404BaseMock               ·      2.977  ·       -0.625  │
 ·································|·············|················
 |  ERC20PermitMock               ·      3.047  ·       -0.621  │
 ·································|·············|················
 |  DiamondWritableMock           ·      3.888  ·       -0.909  │
 ·································|·············|················
 |  SolidStateERC20Mock           ·      4.389  ·       -0.902  │
 ·································|·············|················
 |  SolidStateERC1404Mock         ·      4.991  ·       -0.997  │
 ·································|·············|················
 |  ERC4626BaseMock               ·      5.237  ·       -0.811  │
 ·································|·············|················
 |  DiamondReadableMock           ·      5.315  ·       -0.909  │
 ·································|·············|················
 |  ERC721EnumerableMock          ·      5.369  ·       -1.012  │
 ·································|·············|················
 |  ERC721BaseMock                ·      5.802  ·       -0.949  │
 ·································|·············|················
 |  ERC1155BaseMock               ·      6.703  ·       -0.912  │
 ·································|·············|················
 |  SolidStateERC4626Mock         ·      6.840  ·       -1.183  │
 ·································|·············|················
 |  ERC1155EnumerableMock         ·      6.915  ·       -0.963  │
 ·································|·············|················
 |  SolidStateERC721Mock          ·      7.073  ·       -1.266  │
 ·································|·············|················
 |  SolidStateDiamondMock         ·      7.096  ·       -0.979  │
 ·································|·············|················
 |  SolidStateERC1155Mock         ·      7.904  ·       -0.963  │
 ·--------------------------------|-------------|---------------·
```
</details>

**Comment by Lumyo** [comment]
image

@ItsNickBarry I still have those 2 tests failing but im not sure why they fail.
There are still a few revert strings left, mainly in `AddressUtils`, and in some other contracts using this library, as those functions expect `string`

**Comment by wiasliaw** [comment]
I had bumped the test in the same test case.

- https://github.com/solidstate-network/solidstate-solidity/blob/88edf157bb42bd392ca8c7711c929919f4c24016/test/factory/Factory.ts#L82-L84

**Review by NouDaimon — APPROVED** [review]

**Comment by 0xCourtney** [comment]
Was [this](https://github.com/solidstate-network/solidstate-solidity/blob/error-types/contracts/proxy/diamond/readable/DiamondReadable.sol#L51) intentionally left as a `require` statement?

**Comment by Lumyo** [comment]
> Was [this](https://github.com/solidstate-network/solidstate-solidity/blob/error-types/contracts/proxy/diamond/readable/DiamondReadable.sol#L51) intentionally left as a `require` statement?

Yes, thought it was fine to leave it like that, as this require has no revert string, and this PR main purpose was to reduce unnecessary contract size taken by revert strings. Also this particular error is extremely unlikely to ever occur.

**Review by 0xCourtney — APPROVED** [review]
LGTM

**Comment by ItsNickBarry** [comment]
@NouDaimon @0xCourtney Please take a look at the new commits I pushed if you have some time.  Mostly related to visibility layers pattern.

**Review by NouDaimon — APPROVED** [review]

**Pull request merged**
